# Auto-generated by fortran_deps.tcl — do not edit manually
# Run: tclsh9.1 fortran_deps.tcl [src_dir [out_file [entry.f90 ...]]

$(ODIR)/linked_list_sm.o: $(ODIR)/linked_list.mod
$(ODIR)/numerical_sm.o: $(ODIR)/numerical.mod
$(ODIR)/rpn_stack.o: $(ODIR)/numerical.mod
$(ODIR)/rpn_stack_sm.o: $(ODIR)/rpn_stack.mod $(ODIR)/numerical.mod
